name: facebook_messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  glassmorphism: ^3.0.0
  flutter_slidable: ^1.2.0
  badges: ^2.0.2
  shared_preferences: ^2.0.12
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sf Display Pro
      fonts:
        - asset: assets/fonts/Sf_Display_Pro.ttf
